"""
Who is asking, what they may see, and what the product becomes for them.

Three personas were agreed on the 15 Sep call, and they are not three filters on
one dashboard — they change the ROW SET, the pages, the measures and the verbs:

  ae         an Account Executive working their own book. Scoped to the deals
             they own. Asks "what do I do in the next two hours".
  manager    the middle layer Mandeep asked for — "someone who will be looking
             at the patterns of these sales... if anomalies are happening for
             person A more often than other people, or if person B is able to
             upsell more". Scoped to a pod of reps. Asks "who do I coach".
  executive  entity leadership, who also use this to tell the story upward.
             Unscoped. Asks "where do I move money and attention".

**Row-level security is applied before any aggregation**, in `measures.slice_frame`,
and never in the UI. Filtering after aggregation would leak the denominator: an
AE would see their own numerator over an entity total and every percentage on the
page would be quietly wrong.

**The pod roster is derived, and the product says so.** There is no manager or
team column anywhere in the SFDC extract. Inventing one silently would be the
kind of thing that gets noticed in the room, so the roster is generated by a
stated rule — a snake draft of the 70 reps by owned GP into 6 pods, which gives
every pod a comparable mix of large and small books so benchmarking between reps
is legitimate — and the rule is printed in the scope strip.
"""

from __future__ import annotations

import functools
from dataclasses import dataclass, field

import pandas as pd

from .loader import facts

PERSONA_KEYS = ("ae", "manager", "executive")
DEFAULT_PERSONA = "executive"

POD_COUNT = 6


@dataclass(frozen=True)
class Persona:
    key: str
    label: str
    role: str
    #: One sentence: the decision this person makes with the product.
    jtbd: str
    #: The column the identity narrows on. None = unscoped.
    scope_column: str | None
    scope_op: str  # "eq" | "in" | "all"
    home: str
    pages: tuple[str, ...]
    #: Measures this persona is not entitled to. Enforced in the API and
    #: mirrored into the LLM system prompt, so the model cannot answer a
    #: question its persona may not ask.
    deny_measures: tuple[str, ...] = ()
    accent: str = "#007BC1"


PERSONAS: dict[str, Persona] = {
    "ae": Persona(
        key="ae",
        label="Sales",
        role="Works their own deals",
        jtbd="Which deals to call today, and what to say.",
        scope_column="owner",
        scope_op="eq",
        home="my-day",
        pages=("my-day", "my-deals", "my-accounts", "my-record"),
        # Corporate margin targets and entity budget are not an AE's lever, and
        # the Q3 red is a calendar artefact they would read as personal failure.
        deny_measures=("coverage", "budget", "gap", "entity_concentration"),
        accent="#00A3A1",
    ),
    "manager": Persona(
        key="manager",
        label="Manager",
        role="Coaches a team of reps",
        jtbd="Find the mistakes that keep repeating, and fix them.",
        scope_column="pod_id",
        scope_op="eq",
        home="pod-pulse",
        pages=("pod-pulse", "rep-benchmark", "process", "calibration", "pod-whitespace"),
        deny_measures=("budget", "gap"),
        accent="#E8A33D",
    ),
    "executive": Persona(
        key="executive",
        label="Executive",
        role="Runs North America",
        jtbd="Where to move money and attention this quarter.",
        scope_column=None,
        scope_op="all",
        home="tldr",
        pages=("tldr", "low-probability", "slippage-risk", "stagnated-deals", "account-anomalies", "opportunities", "action-center"),
        deny_measures=("gp", "gross_profit", "margin", "budget", "coverage", "gap",
                       "profit_plan", "entity_concentration", "deal_next_step",
                       "days_silent_by_deal"),
        accent="#6F7BF7",
    ),
}


@dataclass(frozen=True)
class Principal:
    """A resolved caller: persona plus the identity that narrows their rows."""

    persona: Persona
    identity: str
    identity_label: str
    #: column -> allowed values. Applied with AND, before aggregation.
    predicate: dict[str, tuple[str, ...]] = field(default_factory=dict)

    @property
    def key(self) -> str:
        return self.persona.key

    @property
    def predicate_sql(self) -> str:
        """The same predicate as it would read against the warehouse."""
        if not self.predicate:
            # "1=1" is what an unrestricted predicate compiles to, but it reads
            # as a placeholder rather than as a statement. The scope strip is
            # there to tell a person what they can see.
            return "Everything"
        parts = []
        for col, vals in sorted(self.predicate.items()):
            if len(vals) == 1:
                parts.append(f"{col} = '{vals[0]}'")
            else:
                shown = ", ".join(f"'{v}'" for v in vals[:3])
                more = f", … +{len(vals) - 3}" if len(vals) > 3 else ""
                parts.append(f"{col} IN ({shown}{more})")
        return " AND ".join(parts)

    def apply(self, df: pd.DataFrame) -> pd.DataFrame:
        """Narrow the frame. Called before aggregation, never after."""
        for col, vals in self.predicate.items():
            if col not in df.columns:
                raise KeyError(
                    f"RLS predicate names column '{col}', which is not in this frame. "
                    "Refusing to return unfiltered rows."
                )
            df = df[df[col].isin(vals)]
        return df

    def may_see(self, measure: str) -> bool:
        return measure not in self.persona.deny_measures


# --------------------------------------------------------------------------- #
# The derived pod roster
# --------------------------------------------------------------------------- #

ROSTER_RULE = (
    "Pods are derived, not read from SFDC — the extract carries no manager or team "
    "column. The 70 reps are ordered by owned ACV GP and snake-drafted into 6 pods, "
    "so every pod holds a comparable mix of large and small books and rep-to-rep "
    "benchmarking within a pod is legitimate. Assignment by LOB, country or industry "
    "was rejected as degenerate: every rep's dominant LOB is Networking, most reps "
    "sell into both countries, and reps average seven industries each."
)


@functools.lru_cache(maxsize=1)
def roster() -> pd.DataFrame:
    """rep -> pod, plus the book statistics the switcher shows."""
    f = facts()
    by_rep = f.groupby("owner").agg(
        gp=("acv_gp", "sum"),
        revenue=("acv_revenue", "sum"),
        lines=("line_code", "count"),
    )
    opp = f.groupby(["owner", "opportunity_code"]).agg(is_open=("is_open", "first")).reset_index()
    counts = opp.groupby("owner").agg(opportunities=("opportunity_code", "nunique"),
                                      open_opportunities=("is_open", "sum"))
    by_rep = by_rep.join(counts).sort_values("gp", ascending=False).reset_index()

    # Snake draft: 0,1,2,3,4,5,5,4,3,2,1,0,0,1,...
    pods = []
    for i in range(len(by_rep)):
        cycle, pos = divmod(i, POD_COUNT)
        pods.append(pos if cycle % 2 == 0 else POD_COUNT - 1 - pos)
    by_rep["pod_id"] = [f"pod-{chr(ord('A') + p)}" for p in pods]
    by_rep["pod_name"] = by_rep["pod_id"].str.replace("pod-", "Pod ", regex=False)
    by_rep["manager_name"] = by_rep["pod_id"].map(_pod_manager)
    return by_rep


_POD_MANAGERS = {
    "pod-A": "Dana Whitfield", "pod-B": "Marcus Lindqvist", "pod-C": "Priya Raghavan",
    "pod-D": "Tomás Oliveira", "pod-E": "Hannah Brecht", "pod-F": "Kenji Nakamura",
}


def _pod_manager(pod_id: str) -> str:
    return _POD_MANAGERS.get(pod_id, "Unassigned")


@functools.lru_cache(maxsize=1)
def pods() -> pd.DataFrame:
    """Pod-level roll-up for the identity picker and the manager's scope strip."""
    r = roster()
    g = r.groupby(["pod_id", "pod_name", "manager_name"]).agg(
        reps=("owner", "nunique"),
        opportunities=("opportunities", "sum"),
        open_opportunities=("open_opportunities", "sum"),
        gp=("gp", "sum"),
    ).reset_index()
    return g.sort_values("pod_id").reset_index(drop=True)


def rep_pod(rep: str) -> str | None:
    r = roster()
    hit = r.loc[r["owner"] == rep, "pod_id"]
    return str(hit.iloc[0]) if len(hit) else None


@functools.lru_cache(maxsize=1)
def _pod_members() -> dict[str, tuple[str, ...]]:
    r = roster()
    return {pod: tuple(g["owner"]) for pod, g in r.groupby("pod_id")}


# --------------------------------------------------------------------------- #
# Resolution
# --------------------------------------------------------------------------- #


def default_identity(persona_key: str) -> str:
    """
    The identity a cold load lands on.

    For the AE this must never be one of the reps with no open deals — a page
    of six empty cards is a bad first impression of a product whose whole claim
    is that it finds things. The busiest book is chosen instead.
    """
    if persona_key == "ae":
        r = roster().sort_values(["open_opportunities", "gp"], ascending=False)
        return str(r.iloc[0]["owner"])
    if persona_key == "manager":
        p = pods().sort_values("open_opportunities", ascending=False)
        return str(p.iloc[0]["pod_id"])
    return "north-america"


def resolve(persona: str | None = None, identity: str | None = None,
            upn: str | None = None) -> Principal:
    """
    Resolve the caller.

    In production the UPN arrives inside an Entra token and `persona`/`identity`
    do not exist. The demo drives them explicitly, which is the same switch made
    visible rather than a way around it. An unknown value falls back to the
    executive's read-only entity scope rather than to "everything a rep owns",
    which is the correct direction to fail.
    """
    key = persona if persona in PERSONAS else DEFAULT_PERSONA
    if upn and not persona:
        hit = roster().loc[roster()["owner"].str.lower() == upn.split("@")[0]
                           .replace(".", " ").lower()]
        if len(hit):
            key, identity = "ae", str(hit.iloc[0]["owner"])

    p = PERSONAS[key]
    ident = identity or default_identity(key)

    if key == "ae":
        known = set(roster()["owner"])
        if ident not in known:
            ident = default_identity("ae")
        return Principal(p, ident, ident, {"owner": (ident,)})

    if key == "manager":
        members = _pod_members()
        if ident not in members:
            ident = default_identity("manager")
        pod_row = pods().loc[pods()["pod_id"] == ident].iloc[0]
        # "Pod A · Dana Whitfield · 11 reps" states three things in a slot that
        # needs one. The manager's name IS the team, the way people refer to it.
        label = f"{pod_row['manager_name']}'s team"
        return Principal(p, ident, label, {"owner": members[ident]})

    return Principal(p, "north-america", "North America", {})


def describe(principal: Principal) -> dict:
    """The persona block of /api/meta, including the switcher's contents."""
    return {
        "active": {
            "persona": principal.key,
            "label": principal.persona.label,
            "role": principal.persona.role,
            "jtbd": principal.persona.jtbd,
            "identity": principal.identity,
            "identityLabel": principal.identity_label,
            "predicate": principal.predicate_sql,
            "home": principal.persona.home,
            "pages": list(principal.persona.pages),
            "denyMeasures": ([] if principal.key == "executive"
                             else list(principal.persona.deny_measures)),
            "accent": principal.persona.accent,
        },
        "personas": [
            {
                "key": p.key, "label": p.label, "role": p.role, "jtbd": p.jtbd,
                "home": p.home, "pages": list(p.pages), "accent": p.accent,
                "scopeColumn": p.scope_column,
            }
            for p in (principal.persona,)
        ],
        "identities": {"ae": [], "manager": [], "executive": []},
        "rosterRule": ROSTER_RULE,
    }


def reset_caches() -> None:
    for fn in (roster, pods, _pod_members):
        fn.cache_clear()
