"""Server-only demo account registry and password hashing."""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import secrets
from functools import lru_cache
from pathlib import Path

from config import ROOT


ITERATIONS = 600_000


def registry_path() -> Path:
    return Path(
        os.environ.get(
            "NTT_DEMO_ACCOUNTS_FILE",
            ROOT / ".demo-accounts.json",
        )
    )


@lru_cache(maxsize=1)
def load_registry() -> dict:
    """
    Load demo accounts.

    Local development:
        Uses .demo-accounts.json generated by setup_demo_accounts.

    Deployment:
        If the file does not exist, an Executive demo account can be
        configured entirely through environment variables.
    """

    path = registry_path()

    # ---------------------------------------------------------------
    # 1. Existing local/file-based configuration
    # ---------------------------------------------------------------
    try:
        data = json.loads(path.read_text(encoding="utf-8"))

        if (
            data.get("version") != 1
            or not data.get("signingSecret")
            or not isinstance(data.get("accounts"), list)
        ):
            raise ValueError("Invalid registry")

        return data

    except (OSError, ValueError, TypeError):
        pass

    # ---------------------------------------------------------------
    # 2. Deployment fallback — Executive demo account
    # ---------------------------------------------------------------
    email = os.environ.get(
        "NTT_EXECUTIVE_EMAIL",
        "",
    ).strip().lower()

    password = os.environ.get(
        "NTT_EXECUTIVE_PASSWORD",
        "",
    )

    access_secret = os.environ.get(
        "NTT_ACCESS_SECRET",
        "",
    ).strip()

    if email and password and access_secret:
        return {
            "version": 1,
            "signingSecret": access_secret,
            "accounts": [
                {
                    "id": "executive-na",
                    "name": "North America Executive",
                    "email": email,
                    "aliases": [],
                    "role": "executive",
                    "identity": "north-america",
                    "enabled": True,
                    "passwordHash": hash_password(password),
                }
            ],
        }

    raise RuntimeError(
        "Demo accounts are not configured. "
        "Configure NTT_EXECUTIVE_EMAIL, "
        "NTT_EXECUTIVE_PASSWORD and NTT_ACCESS_SECRET."
    )


def hash_password(password: str) -> str:
    salt = secrets.token_hex(16)

    digest = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode(),
        salt.encode(),
        ITERATIONS,
    ).hex()

    return f"pbkdf2_sha256${ITERATIONS}${salt}${digest}"


def check_password(password: str, encoded: str) -> bool:
    try:
        scheme, iterations, salt, expected = encoded.split("$")

        if (
            scheme != "pbkdf2_sha256"
            or not 100_000 <= int(iterations) <= 1_000_000
        ):
            return False

        actual = hashlib.pbkdf2_hmac(
            "sha256",
            password.encode(),
            salt.encode(),
            int(iterations),
        ).hex()

        return hmac.compare_digest(actual, expected)

    except (ValueError, TypeError):
        return False


def find_by_email(registry: dict, email: str) -> dict | None:
    normalized = email.strip().lower()

    return next(
        (
            account
            for account in registry["accounts"]
            if normalized
            in [
                account["email"],
                *account.get("aliases", []),
            ]
            and account.get("enabled", True)
        ),
        None,
    )


def find_by_id(registry: dict, account_id: str) -> dict | None:
    return next(
        (
            account
            for account in registry["accounts"]
            if account["id"] == account_id
            and account.get("enabled", True)
        ),
        None,
    )